[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "broadcast-server"
version = "0.1.0"
description = ""
requires-python = ">=3.14" 
dependencies = [
    "fastapi>=0.140.0",
    "uvicorn[standard]>=0.52.0",
    "redis>=8.1.0",
    "pydantic-settings>=2.15.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "httpx2",
]

[tool.setuptools]
packages = ["app"]